FROM nginx:stable-alpine

# copy deafult.conf to /etc/nginx/conf.d
COPY default.conf /etc/nginx/conf.d

EXPOSE 80/tcp
EXPOSE 443/tcp

CMD ["/bin/sh", "-c", "exec nginx -g 'daemon off;';"]

# set the current working directory to /usr/share/nginx/html
WORKDIR /usr/share/nginx/html
